# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: DTMKlxj199866
  http:
    encoding:
      charset: utf-8
      force: true
shiro-redis:
  enabled: true
  redis-manager:
    host: redis:6379